runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.well-known
  static_dir: dot-well-known
- url: /keybase.txt
  secure: always
  static_files: keybase.txt
  upload: keybase.txt
- url: /index.css
  secure: always
  static_files: index.css
  upload: index.css
- url: /resume.pdf
  secure: always
  static_files: resume.pdf
  upload: resume.pdf
- url: /
  secure: always
  static_files: index.html
  upload: index.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.fossil$
