* The Absence of Miriam Lane
* Admiration Point
* Thanatophobia
* A Matter of Heist Urgency
* The Lottery Ticket
** Finished [2022-11-14 Mon].
** Rated 4.
** Noted.
I am quite intrigued by the presentation of this kind of narrative, even though
what it asked of me was uneven and I have little desire to revisit it. The most
interesting thread to pull on (I admit thanks to non-IFComp reading and
thinking) is that of time, but both stories are presented in straightforward
linear fashion, and the opportunities for interaction appear small between long
blocks of text. I do feel like my attention was demanded and well-used on the
Chekhov, but there's so much less characterization in the frame story and no
good way to put myself in there.
* The Alchemist
* The Thirty Nine Steps
* i wish you were dead.
* The Hidden King's Tomb
** Finished [2022-11-14 Mon].
** Rated 3.
** Noted.
This game has one of the most economic blurbs I've seen in IFComp, just enough
to put my slightly off-balance but whet the appetite for a classic cave
crawl. The prose was quite pleasant; I look forward to checking out Counsel and
hopeful future parser efforts. This cave, though, is a setpiece which wants
another layer of implementation. The verb-guess is very classic, but the puzzle
solution feels slapped-on-the-end given the size of the entire environment. The
skeleton types were great touches, though! And I enjoyed the secondary tombs
even though they seemed less than connected to solutions.
* A Walk Around the Neighborhood
* U.S. Route 160
* Through the Forest with the Beast
* Death by Lightning
* Graveyard Strolls
* Star Tripper
* The Only Possible Prom Dress
* An Alien's Mistaken Impressions of Humanity's Pockets
* Who Shot Gum E. Bear?
** Finished [2022-11-04 Fri].
** Rated 6.
** Noted.
The prose was a delight, making my final verdict "a fine piece of minimalist
detective noir". I did run into a problem that seems common (since I had to
read reviews to finish): There is little connection between most of the game
and the solution. I slept on that and realized it isn't /technically/ true. The
key to the mystery is given early, and nibbled at my brain throughout my
playthrough. It was emphasized by unfamiliar but pervasive hinting. I felt
stupid because of what appear still to be red herrings and locked doors, and
that's something I never want to feel at the end of a mystery game. But in the
end I have to respect the cleverness of the solution. A slightly smoother
implementation or pertinent help text would do a lot for this one.
* Zero Chance of Recovery
* Lost Coastlines
* CHASE THE SUN
* Approaching Horde!
* Campus Invaders
* Crash
* One Way Ticket
* Prism
* January
* A Long Way to the Nearest Star
* Glimmer
* You May Not Escape!
* Nose Bleed
** Finished [2022-11-04 Fri].
** Rated 8.
** Noted.
The limited palette is still viscerally effective. The visual design and coding
squeeze everything out of Texture they can, and while I hate hunt-the-pixel
games, it worked well enough for me to use all three draggables. It's hard to
find something this focused and this good, though I felt the text acted as more
of a gimmick than as fiction per se.
* Use Your Psychic Powers at Applebee's
* You Feel Like You've Read this in a Book
* The Last Christmas Present
* Traveller's Log
* Headlights
* HOURS
* A Chinese Room
* Esther's
* The Archivist and the Revolution
* Am I My Brother's Keeper?
* The Counsel in The Cave
* Lucid
** Finished [2022-11-14 Mon].
** Rated 8.
** Noted.
I started reading the author's Substack and guessed correctly that this would
be exactly up my alley. Extremely pleased with that, and with the fact that the
path I took ended up feeling perfect, almost cozy, if you could call Lucid
that. The only nitpicks I have are about its/it's confusion and the barebones
styling. There is a nice switch-up at the end, though, which dovetailed
perfectly with my opening explorations. Lucid reminds me of The good people,
the first Pseudavid game I played, blurring the game-hypertext line by letting
you explore a narrative space in Twine. I have complicated feelings about the
gameness of games like that, but when the first-play experience is this
immaculate, I have to admit there's still room for it to grow on me.
* Trouble in Sector 471
* Blood Island
* Let Them Eat Cake
* Elvish for Goodbye
* Jungle adventure
* According to Cain
* The Grown-Up Detective Agency
* Hanging by threads
* The Staycation
* INK
* No One Else Is Doing This
* Into The Sun
* One Final Pitbull Song (at the End of the World)
* The Thick Table Tavern
* Under the Bridge
* The Princess of Vestria
* Witchfinders
** Finished [2022-11-04 Fri].
** Rated 4.
** Noted.
Formally, I expected to really dislike the simple task loop. Happily, the world
is fleshed out with additional scenes which make me happy I spent some time in
the world. I found the cattle solution second, by stumbling onto its solution
more or less randomly. I may revisit the game to see the failure condition
because it felt easier to get stuck than to lose altogether. The "house rules"
are just enough shine on the Twine part: Besides that, it feels like a very
straightforward IFComp choice game. I hope we see more!
* Tower of Plargh
* The Tin Mug
* Lazy Wizard's Guide
* Inside
* Low-Key Learny Jokey Journey
* The Pool
* Arborea
* To Persist/Exist/Endure, Press 1
* 4 Edith + 2 Niki
* Cannelé & Nomnom - Defective Agency
* Lost at the market
