* After-Words
** Finished [2021-11-15 Mon].
** Rated 6.
** Noted.
The game succeeds on being evocative, and that's in no small part thanks to the
map. It's beautiful in an understated way, and the clipped descriptions would
mean a lot less without the colors and symbols to guide the eye, and gaps that
guide the mind into filling them up. I was worried at first that the
puzzle-solving would be too linear. That was unfounded (for the most part): The
gameplay got much more interesting once multiple gates were revealed. However,
at the end of each path is an "X Resolution", which kills the poetry of the
setting and makes it feels closed-in again. The other negative was the
interface: I quite enjoyed clicking through descriptions after I figured out
how merciful the engine was, but don't think the modal interaction works. Maybe
it would be less arduous on a phone or with a mouse, but it was a lot of small
clicks on a trackpad. Let me reemphasize that having room descriptions
expandable in multiple ways was a plus for me: I've seen other reviews which
criticize that aspect. I did fall back on a brute force pattern at times: Look
to maximum depth, then Interact back down. My brute force attempts at items in
rooms were my failure and not the game's.
* The daughter
* An Aside About Everything
* A Papal Summons, or The Church Cat
* My Gender Is a Fish
* Plane Walker
* Off-Season at the Dream Factory
* Brave Bear
* Beneath Fenwick
* BLK MTN
* The Belinsky Conundrum
* Cyborg Arena
* The Waiting Room
* Codex Sadistica
* The Libonotus Cup
* The Vaults
* 4x4 Archipelago
* You Are SpamZapper 3.1
* The House on Highfield Lane
* The TURING Test
* Second Wind
* Taste of Fingers
* Mermaids of Ganymede
* Hercules!
* Wabewalker
* The Last Doctor
* Enveloping Darkness
* This Won't Make You Happy
* The Golden Heist
* Infinite Adventure
* And Then You Come to a House Not Unlike the Previous One
* At King Arthur's Christmas Feast
* The Miller's Garden
* How it was then and how it is now
* D'ARKUN
* Grandma Bethlinda's Remarkable Egg
* Finding Light
* The Library
* Fourbyfourian Quarryin'
* Closure
* The Corsham Witch Trial
* Ghosts Within
* Weird Grief
* RetroCON 2021
* The Dead Account
* Silicon and Cells
* What remains of me
* I Contain Multitudes
* The Spirit Within Us
* we, the remainder
* Recon
* Unfortunate
* The Best Man
* How the monsters appeared in the Wasteland
* Kidney Kwest
* extraordinary_fandoms.exe
* The Last Night of Alexisgrad
* Funicular Simulator 2021
* Dr Horror's House of Terror
* Starbreakers
* Cygnet Committee
* Walking Into It
* What Heart Heard Of, Ghost Guessed
* Universal Hologram
* Smart Theory
* The Song of the Mockingbird
* Fine Felines
* Goat Game
* Sting
* A Paradox Between Worlds
* AardVarK Versus the Hype
