* After-Words
** Finished [2021-11-15 Mon].
** Rated 6.
** Noted.
The game succeeds on being evocative, and that's in no small part thanks to the
map. It's beautiful in an understated way, and the clipped descriptions would
mean a lot less without the colors and symbols to guide the eye, and gaps that
guide the mind into filling them up. I was worried at first that the
puzzle-solving would be too linear. That was unfounded (for the most part): The
gameplay got much more interesting once multiple gates were revealed. However,
at the end of each path is an "X Resolution", which kills the poetry of the
setting and makes it feels closed-in again. The other negative was the
interface: I quite enjoyed clicking through descriptions after I figured out
how merciful the engine was, but don't think the modal interaction works. Maybe
it would be less arduous on a phone or with a mouse, but it was a lot of small
clicks on a trackpad. Let me reemphasize that having room descriptions
expandable in multiple ways was a plus for me: I've seen other reviews which
criticize that aspect. I did fall back on a brute force pattern at times: Look
to maximum depth, then Interact back down. My brute force attempts at items in
rooms were my failure and not the game's.
* The daughter
* An Aside About Everything
* A Papal Summons, or The Church Cat
* My Gender Is a Fish
** Finished [2021-11-15 Mon].
** Rated 4.
** Noted.
The prose was nice enough, and the impact of the choices felt smooth and not
pasted-in. The problem is how little impact they have on the interactivity. I
thought it was a fine Twine essay with hypertext sprinkles. I think it would be
interesting to have a more leisurely procession of sensations, but am not sure
how to do it without adding more choiceless choices.
* Plane Walker
* Off-Season at the Dream Factory
* Brave Bear
* Beneath Fenwick
* BLK MTN
* The Belinsky Conundrum
* Cyborg Arena
* The Waiting Room
* Codex Sadistica
* The Libonotus Cup
* The Vaults
* 4x4 Archipelago
* You Are SpamZapper 3.1
* The House on Highfield Lane
* The TURING Test
* Second Wind
* Taste of Fingers
* Mermaids of Ganymede
* Hercules!
* Wabewalker
* The Last Doctor
* Enveloping Darkness
** Finished [2021-11-15 Mon].
** Rated 3.
** Noted.
There were no noticeable errors, and the interface was smooth. However, the
choices started to feel pointless early on, and by the end the lack of choice
at all started to glare. It was around that point that I started to realize
that the protagonist's affect seemed to be determined more by the plot than my
input.
* This Won't Make You Happy
** Finished [2021-11-15 Mon].
** Rated 4.
** Noted.
I thought this was unfinished-not-incomplete and a bit too cute for its own
good. I finished Piranesi recently and appreciated the World speaking; The
edibility of nouns was just right. I hope the author enjoyed making the more
gonzo PowerPoint transitions, but am skeptical about their merit.
* The Golden Heist
* Infinite Adventure
* And Then You Come to a House Not Unlike the Previous One
* At King Arthur's Christmas Feast
* The Miller's Garden
** Finished [2021-11-15 Mon].
** Rated 5.
** Noted.
I rather enjoyed the meditative nature inherent to gardening games. The
deformation of the graphics is a really neat piece of tech, and makes the most
of the limited choice space. I didn't love being forced through each zone over
and over, especially as the closest one was a lawn.
* How it was then and how it is now
* D'ARKUN
* Grandma Bethlinda's Remarkable Egg
* Finding Light
* The Library
* Fourbyfourian Quarryin'
* Closure
* The Corsham Witch Trial
* Ghosts Within
* Weird Grief
* RetroCON 2021
* The Dead Account
* Silicon and Cells
* What remains of me
* I Contain Multitudes
* The Spirit Within Us
* we, the remainder
* Recon
* Unfortunate
* The Best Man
* How the monsters appeared in the Wasteland
* Kidney Kwest
* extraordinary_fandoms.exe
* The Last Night of Alexisgrad
* Funicular Simulator 2021
* Dr Horror's House of Terror
* Starbreakers
* Cygnet Committee
* Walking Into It
* What Heart Heard Of, Ghost Guessed
* Universal Hologram
* Smart Theory
* The Song of the Mockingbird
* Fine Felines
* Goat Game
* Sting
* A Paradox Between Worlds
* AardVarK Versus the Hype
