* The Paper Magician
** Finished [2023-11-15].
** Rated 4.
** Noted.
Other reviews have discussed the impact of Twine in two key areas, and they're
right. Funnily enough, the short length of the game made the navigation
fiddliness almost charming: It would have been great as a small part of a
longer game. That's the theme of my impression, really, grousing about the
choice of choice for a short puzzler aside. The prose in certain sections is
obviously more-worked, the dash of art at the end has quite a nice
effect. However, the de facto Guess The Verb and featureless hallways were pure
downsides, and the quarantining of magic to linear sections prevented me from
wanting to play again.
* Detective Osiris
* Put Your Hand Inside The Puppet Head
* Artful Deceit
* Kaboom
* The Gift of What You Notice More
* The Long Kill
* Escape your psychosis
* One Knight Stand
* Milliways: the Restaurant at the End of the Universe
* Help! I Can't Find My Glasses!
* DICK MCBUTTS GETS KICKED IN THE NUTS
** Finished [2023-11-15].
** Rated 7.
** Noted.
I feel secure in comparing this to my experience of Turandot a few years ago,
despite (I'm afraid) the visual inferiority. The halves play against each other
well, especially since the WordArt effects are anything but tossed-off. The
longer narrative felt rather linear, but did reward me for what felt like
reasonable choices. Many standout turns of phrase; I found "swastika of pain"
hit harder than any of the testicular ones. DICK MCBUTTS is under total
authorial control, and that makes him cozy, even in spartan environs of limited
interactivity.
* Last Valentine's Day
* The Little Match Girl 4
* Meritocracy
* One Does Not Simply Fry
* Hand Me Down
* Assembly
* Tricks of light in the forest
** Finished [2023-11-08].
** Rated 6.
** Noted.
Tricks of light is from a favorite (wish I could say perennial, but I think
that I have in fact only played Pseudavid's The good people, which I adored)
and an auspicious starting point, as I noted CMG starting with its review but
not who CMG was (another favorite, it turns out). The game is a too-appropriate
companion to my last book club book, which generated similar reactions for
similar reasons. The (evidently Gruescript) form works well here, but is also
somewhat frustrating for a parser-focused player: There's a lot of work in the
subtleties of retracing steps. The game does capture perfectly the feeling of a
venture just too far into the forest: Too well in "scoring terms", if the
player feels the parental rules pressing on them. The affordances for reading
and interacting have just a bit too much friction, especially the switching-to
and reading-of the map. Narrative flow, as such, is linear, but it really seems
that that isn't the point, and the mood of the piece is very near
seamless. Even played fast, as I sinfully did. I'm not a particular good child,
both Tricks and the Blue Book demonstrate.
* Honk!
* Virtue
* Please Sign Here
* We All Fall Together
* The Whale's Keeper
** Finished [2023-11-15 Wed]
** Rated 8.
** Noted.
The statistical breadcrumbs suggest that I played wide and shallow, and I did
not expect the grief to arrive so strong or the experience to feel so
complete. The art is very nice, and it would be nicer if there was more of it;
The timed text felt like the weakest technical link, though I ignored the speed
options 'til late. (There were a couple minor issues where the bot seemed to
pick up my last command instead of printing the new options.) Jonah has plenty
of religious resonance. The game was very respectful of the choice to avoid
horror, or just telegraphed what it didn't have.
* Xanthippe's Last Night with Socrates
* Antony & Cleopatra: Case IV: The Murder of Marlon Brando
* Dr Ludwig and the Devil
* Eat the Eldritch
* Trail Stash
* Who Iced Mayor McFreeze?
* Lonehouse
* Bali B&B
* In The Details
* To Sea in a Sieve
* Out of Scope
* Dysfluent
* How Prince Quisborne the Feckless Shook His Title
* My Pseudo-Dementia Exhibition
* The Whisperers
* My Brother; The Parasite
* The Finders Commission
* For Eternity, Again and Again
** Finished [2023-11-15 Wed].
** Rated 2.
** Noted.
The unclear but seemingly meaningless choice between lover and hero sides
turned me away from exploring the advertised branching. The writing was only
rough on a nitpick level, but it also didn't justify the skipping-over of all
heroics. The near-evocation of a video game was neat, though, and hopefully not
something I'm overreading.
* All Hands Abandon Ship
* Hawkstone
* Creative Cooking
* All the Troubles Come My Way
* Shanidar, Safe Return
* Fix Your Mother's Printer
* GameCeption
* The Sculptor
* CODENAME OBSCURA
* LUNIUM
* Barcarolle in Yellow
* Ribald Bat Lady Plunder Quest
* Into The Lion's Mouth
* All Hands
* The Witch
* Beat Witch
* Have Orb, Will Travel
* Magor Investigates...
* Gestures Towards Divinity
* A Thing of Wretchedness
* Bright Brave Knight Knave
* LAKE Adventure
* The Ship
* Death on the Stormrider
* Lake Starlight
* The Engima of Solaris
* One King to Loot them All
* Last Vestiges
* Citizen Makane
* 20 Exchange Place
* The Library of Knowledge
* Paintball Wizard
* The Vambrace of Destiny
