* The Absence of Miriam Lane
* Admiration Point
* Thanatophobia
* A Matter of Heist Urgency
* The Lottery Ticket
* The Alchemist
* The Thirty Nine Steps
* i wish you were dead.
* The Hidden King's Tomb
* A Walk Around the Neighborhood
* U.S. Route 160
* Through the Forest with the Beast
* Death by Lightning
* Graveyard Strolls
* Star Tripper
* The Only Possible Prom Dress
* An Alien's Mistaken Impressions of Humanity's Pockets
* Who Shot Gum E. Bear?
** Finished [2022-11-04 Fri].
** Rated 6.
** Noted.
The prose was a delight, making my final verdict "a fine piece of minimalist
detective noir". I did run into a problem that seems common (since I had to
read reviews to finish): There is little connection between most of the game
and the solution. I slept on that and realized it isn't /technically/ true. The
key to the mystery is given early, and nibbled at my brain throughout my
playthrough. It was emphasized by unfamiliar but pervasive hinting. I felt
stupid because of what appear still to be red herrings and locked doors, and
that's something I never want to feel at the end of a mystery game. But in the
end I have to respect the cleverness of the solution. A slightly smoother
implementation or pertinent help text would do a lot for this one.
* Zero Chance of Recovery
* Lost Coastlines
* CHASE THE SUN
* Approaching Horde!
* Campus Invaders
* Crash
* One Way Ticket
* Prism
* January
* A Long Way to the Nearest Star
* Glimmer
* You May Not Escape!
* Nose Bleed
* Use Your Psychic Powers at Applebee's
* You Feel Like You've Read this in a Book
* The Last Christmas Present
* Traveller's Log
* Headlights
* HOURS
* A Chinese Room
* Esther's
* The Archivist and the Revolution
* Am I My Brother's Keeper?
* The Counsel in The Cave
* Lucid
* Trouble in Sector 471
* Blood Island
* Let Them Eat Cake
* Elvish for Goodbye
* Jungle adventure
* According to Cain
* The Grown-Up Detective Agency
* Hanging by threads
* The Staycation
* INK
* No One Else Is Doing This
* Into The Sun
* One Final Pitbull Song (at the End of the World)
* The Thick Table Tavern
* Under the Bridge
* The Princess of Vestria
* Witchfinders
** Finished [2022-11-04 Fri].
** Rated 4.
** Noted.
Formally, I expected to really dislike the simple task loop. Happily, the world
is fleshed out with additional scenes which make me happy I spent some time in
the world. I found the cattle solution second, by stumbling onto its solution
more or less randomly. I may revisit the game to see the failure condition
because it felt easier to get stuck than to lose altogether. The "house rules"
are just enough shine on the Twine part: Besides that, it feels like a very
straightforward IFComp choice game. I hope we see more!
* Tower of Plargh
* The Tin Mug
* Lazy Wizard's Guide
* Inside
* Low-Key Learny Jokey Journey
* The Pool
* Arborea
* To Persist/Exist/Endure, Press 1
* 4 Edith + 2 Niki
* Cannelé & Nomnom - Defective Agency
* Lost at the market
